### PR TITLE
chore(gltf): Include @loaders.gl/core dependency

### PR DESCRIPTION
**Pull request by felixpalmer**
#### Background

v9.0 PR for https://github.com/visgl/luma.gl/pull/2106

#### Change List
- Include @loaders.gl/core dependency
- Undo lerna changes to allow publish with correct version

### CODE REVIEW

**Comment by felixpalmer** [comment]
@ibgreen it's a [peerDependency](https://github.com/visgl/loaders.gl/blob/master/modules/textures/package.json#L66) so I think we have to include it. However, I think it should be `peerDependency` also. This is what we do in similar situations in deck (e.g. `geo-layers/package.json`) and then it is only the core module which has `loaders.gl/core` in `dependencies`

**Comment by ibgreen** [comment]
> @ibgreen it's a [peerDependency](https://github.com/visgl/loaders.gl/blob/master/modules/textures/package.json#L66) so I think we have to include it. However, I think it should be `peerDependency` also. This is what we do in similar situations in deck (e.g. `geo-layers/package.json`) and then it is only the core module which has `loaders.gl/core` in `dependencies`

Why is it a peerDepencency? Where in the code do we import it? Just searched and I can't find it.

**Review by ibgreen — APPROVED** [review]
OK the bug here seems to be that `@loaders.gl/textures` is including `@loaders.gl/core`. This is something of a policing failure in loaders.gl - where the design is that loader modules generally should not include core. 

I think it is fine to merge this into 9.0-release but for master I'd like to see if I can break the dependency in loaders first.

**Comment by felixpalmer** [comment]
@ibgreen the only place it is used is https://github.com/visgl/loaders.gl/blob/master/modules/textures/bundle.ts, otherwise it is just in tests, so it could be move to a `devDependency`?

**Pull request merged**
