### PR TITLE
fix: Update path to Khrnos glTF assets

### PR DESCRIPTION
**Pull request by ibgreen**
For #

#### Background
- Khronos seems to have broken out their glTF assets from their viewer repo into a separate repo.
#### Change List
- Update path
#### Not done
- We might want to check if there are new assets for us to integrate with

### CODE REVIEW

**Comment by donmccurdy** [comment]
Also: https://github.com/KhronosGroup/glTF-Asset-Generator – these aren't "nice-looking" assets, but they're invaluable for testing technical edge cases.

> We might want to check if there are new assets for us to integrate with

Quite a lot on the glTF feature roadmap this year! Perhaps worth a fuller discussion of what would be in scope for lumagl and loadersgl. Probably some pieces are out of scope (interactivity, behavior graphs, physics) and some would fit very well (everything in 3D Tiles 1.1).

**Review by donmccurdy — APPROVED** [review]

**Review by felixpalmer — APPROVED** [review]

**Comment by ibgreen** [comment]
> Probably some pieces are out of scope (interactivity, behavior graphs, physics) and some would fit very well (everything in 3D Tiles 1.1).

That would be great. 

More urgently we are getting indications that some glTF models fail to load likely because they specify attribute layouts that are disallowed by WebGPU, and luma is presumably now enforcing some of those limits for WebGL as well. We may need an "attribute converter". This could be done in loaders.gl GLTFLoader which already offers a range of glTF post processing options.

**Comment by donmccurdy** [comment]
Hm, I am surprised by that. No changes have been required so far in the three.js GLTFLoader to support WebGPU, and we do not post-process attributes in the loader. Would be happy to look at it (although I am on vacation for the next two weeks). Post-processing attributes sounds very reasonable too; some glTF exporters do write more optimized layouts than others.

**Comment by ibgreen** [comment]
> Hm, I am surprised by that. No changes have been required so far in the three.js GLTFLoader to support WebGPU

Maybe I am just self-confirming my own misguided suspicions when I see issues like this come by: https://github.com/visgl/deck.gl/discussions/8815#discussioncomment-10216384

**Pull request merged**
